# Generated by Django 4.0.4 on 2022-05-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arme',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
